# Generated by Django 3.2.10 on 2022-01-14 09:58

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import pulpcore.app.models.content
import pulpcore.app.models.fields
import pulpcore.app.models.task
import uuid


class Migration(migrations.Migration):

    replaces = [('core', '0001_initial'), ('core', '0002_increase_artifact_size_field'), ('core', '0003_remove_upload_completed'), ('core', '0004_add_duplicated_reserved_resources'), ('core', '0005_progressreport_code'), ('core', '0006_repository_plugin_managed'), ('core', '0007_delete_progress_proxies'), ('core', '0008_published_metadata_as_content'), ('core', '0009_remove_task_non_fatal_errors'), ('core', '0010_pulp_fields'), ('core', '0011_relative_path'), ('core', '0012_auto_20191104_2000'), ('core', '0013_repository_pulp_type'), ('core', '0014_remove_repository_plugin_managed'), ('core', '0015_auto_20191112_1426'), ('core', '0016_charfield_to_textfield'), ('core', '0017_remove_task_parent'), ('core', '0018_auto_20191127_2350'), ('core', '0019_add_signing_service_model'), ('core', '0020_change_publishedartifact_constraints'), ('core', '0021_add_signing_service_foreign_key'), ('core', '0022_rename_last_version')]

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('pulp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('file', pulpcore.app.models.fields.ArtifactFileField(max_length=255, upload_to=pulpcore.app.models.content.Artifact.storage_path)),
                ('size', models.BigIntegerField()),
                ('md5', models.CharField(db_index=True, max_length=32)),
                ('sha1', models.CharField(db_index=True, max_length=40)),
                ('sha224', models.CharField(db_index=True, max_length=56)),
                ('sha256', models.CharField(db_index=True, max_length=64, unique=True)),
                ('sha384', models.CharField(db_index=True, max_length=96, unique=True)),
                ('sha512', models.CharField(db_index=True, max_length=128, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('_created', models.DateTimeField(auto_now_add=True)),
                ('_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_type', models.TextField(default=None)),
            ],
            options={
                'verbose_name_plural': 'content',
            },
            bases=(models.Model, pulpcore.app.models.content.QueryMixin),
        ),
        migrations.CreateModel(
            name='ContentAppStatus',
            fields=[
                ('pulp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.TextField(db_index=True, unique=True)),
                ('last_heartbeat', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContentArtifact',
            fields=[
                ('pulp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('relative_path', models.CharField(max_length=255)),
                ('artifact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.artifact', to_field='pulp_id')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.content')),
            ],
            options={
                'unique_together': {('content', 'relative_path')},
            },
            bases=(models.Model, pulpcore.app.models.content.QueryMixin),
        ),
        migrations.CreateModel(
            name='ContentGuard',
            fields=[
                ('pulp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('pulp_type', models.TextField(default=None)),
                ('name', models.TextField(db_index=True, unique=True)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Exporter',
            fields=[
                ('pulp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('pulp_type', models.TextField(default=None)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('last_export', models.DateTimeField(null=True)),
            ],
            options={
                'default_related_name': 'exporters',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('pulp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('pulp_type', models.TextField(default=None)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
            options={
                'default_related_name': 'publishers',
            },
        ),
        migrations.CreateModel(
            name='Remote',
            fields=[
                ('pulp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('pulp_type', models.TextField(default=None)),
                ('name', models.TextField(db_index=True, unique=True)),
                ('url', models.TextField()),
                ('ca_cert', models.TextField(null=True)),
                ('client_cert', models.TextField(null=True)),
                ('client_key', models.TextField(null=True)),
                ('tls_validation', models.BooleanField(default=True)),
                ('proxy_url', models.TextField(null=True)),
                ('username', models.TextField(null=True)),
                ('password', models.TextField(null=True)),
                ('download_concurrency', models.PositiveIntegerField(default=20)),
                ('policy', models.TextField(choices=[('immediate', 'When syncing, download all metadata and content now.'), ('on_demand', 'When syncing, download metadata, but do not download content now. Instead, download content as clients request it, and save it in Pulp to be served for future client requests.'), ('streamed', 'When syncing, download metadata, but do not download content now. Instead,download content as clients request it, but never save it in Pulp. This causes future requests for that same content to have to be downloaded again.')], default='immediate')),
            ],
            options={
                'default_related_name': 'remotes',
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('_created', models.DateTimeField(auto_now_add=True)),
                ('_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('description', models.TextField(null=True)),
                ('last_version', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'repositories',
            },
        ),
        migrations.CreateModel(
            name='RepositoryVersion',
            fields=[
                ('pulp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('number', models.PositiveIntegerField(db_index=True)),
                ('complete', models.BooleanField(db_index=True, default=False)),
                ('base_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='core.repositoryversion', to_field='pulp_id')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.repository')),
            ],
            options={
                'ordering': ('number',),
                'get_latest_by': 'number',
                'default_related_name': 'versions',
                'unique_together': {('repository', 'number')},
            },
        ),
        migrations.CreateModel(
            name='ReservedResource',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('_created', models.DateTimeField(auto_now_add=True)),
                ('_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('resource', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('_created', models.DateTimeField(auto_now_add=True)),
                ('_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('state', models.TextField(choices=[('waiting', 'Waiting'), ('skipped', 'Skipped'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')])),
                ('name', models.CharField(max_length=255)),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('non_fatal_errors', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('error', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spawned_tasks', to='core.task')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('pulp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('file', models.FileField(max_length=255, upload_to='')),
                ('size', models.BigIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('pulp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.TextField(db_index=True, unique=True)),
                ('last_heartbeat', models.DateTimeField(auto_now=True)),
                ('gracefully_stopped', models.BooleanField(default=False)),
                ('cleaned_up', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UploadChunk',
            fields=[
                ('pulp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('offset', models.BigIntegerField()),
                ('size', models.BigIntegerField()),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='core.upload', to_field='pulp_id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskReservedResource',
            fields=[
                ('pulp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.reservedresource')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.task')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='task',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.worker', to_field='pulp_id'),
        ),
        migrations.AddField(
            model_name='reservedresource',
            name='tasks',
            field=models.ManyToManyField(related_name='reserved_resources', through='core.TaskReservedResource', to='core.Task'),
        ),
        migrations.AddField(
            model_name='reservedresource',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.worker', to_field='pulp_id'),
        ),
        migrations.CreateModel(
            name='RepositoryVersionContentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_type', models.CharField(choices=[('A', 'added'), ('P', 'present'), ('R', 'removed')], max_length=1)),
                ('content_type', models.TextField()),
                ('count', models.IntegerField()),
                ('repository_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counts', to='core.repositoryversion', to_field='pulp_id')),
            ],
        ),
        migrations.CreateModel(
            name='RepositoryContent',
            fields=[
                ('pulp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version_memberships', to='core.content')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.repository')),
                ('version_added', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_memberships', to='core.repositoryversion')),
                ('version_removed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='removed_memberships', to='core.repositoryversion')),
            ],
            options={
                'unique_together': {('repository', 'content', 'version_added'), ('repository', 'content', 'version_removed')},
            },
        ),
        migrations.AddField(
            model_name='repository',
            name='content',
            field=models.ManyToManyField(related_name='repositories', through='core.RepositoryContent', to='core.Content'),
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('pulp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('pulp_type', models.TextField(default=None)),
                ('complete', models.BooleanField(db_index=True, default=False)),
                ('pass_through', models.BooleanField(default=False)),
                ('repository_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.repositoryversion', to_field='pulp_id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('pulp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('message', models.TextField()),
                ('state', models.TextField(choices=[('waiting', 'Waiting'), ('skipped', 'Skipped'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='waiting')),
                ('total', models.IntegerField(null=True)),
                ('done', models.IntegerField(default=0)),
                ('suffix', models.TextField(null=True)),
                ('task', models.ForeignKey(default=pulpcore.app.models.task.Task.current, on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to='core.task')),
                ('code', models.CharField(max_length=36)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreatedResource',
            fields=[
                ('pulp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('object_id', models.UUIDField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('task', models.ForeignKey(default=pulpcore.app.models.task.Task.current, on_delete=django.db.models.deletion.CASCADE, related_name='created_resources', to='core.task')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='content',
            name='_artifacts',
            field=models.ManyToManyField(through='core.ContentArtifact', to='core.Artifact'),
        ),
        migrations.CreateModel(
            name='BaseDistribution',
            fields=[
                ('pulp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('pulp_type', models.TextField(default=None)),
                ('name', models.TextField(db_index=True, unique=True)),
                ('base_path', models.TextField(unique=True)),
                ('content_guard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.contentguard', to_field='pulp_id')),
                ('remote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.remote', to_field='pulp_id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProgressBar',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.progressreport',),
        ),
        migrations.CreateModel(
            name='ProgressSpinner',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.progressreport',),
        ),
        migrations.CreateModel(
            name='RemoteArtifact',
            fields=[
                ('pulp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('url', models.TextField(validators=[django.core.validators.URLValidator])),
                ('size', models.IntegerField(null=True)),
                ('md5', models.CharField(max_length=32, null=True)),
                ('sha1', models.CharField(max_length=40, null=True)),
                ('sha224', models.CharField(max_length=56, null=True)),
                ('sha256', models.CharField(max_length=64, null=True)),
                ('sha384', models.CharField(max_length=96, null=True)),
                ('sha512', models.CharField(max_length=128, null=True)),
                ('content_artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contentartifact', to_field='pulp_id')),
                ('remote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.remote', to_field='pulp_id')),
            ],
            options={
                'unique_together': {('content_artifact', 'remote')},
            },
            bases=(models.Model, pulpcore.app.models.content.QueryMixin),
        ),
        migrations.CreateModel(
            name='PublishedMetadata',
            fields=[
                ('relative_path', models.CharField(max_length=255)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_metadata', to='core.publication')),
                ('content_ptr', models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='published_metadata', serialize=False, to='core.content')),
            ],
            options={
                'default_related_name': 'published_metadata',
                'unique_together': {('publication', 'relative_path')},
            },
        ),
        migrations.CreateModel(
            name='PublishedArtifact',
            fields=[
                ('pulp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('relative_path', models.TextField()),
                ('content_artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_artifact', to='core.contentartifact', to_field='pulp_id')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_artifact', to='core.publication', to_field='pulp_id')),
            ],
            options={
                'default_related_name': 'published_artifact',
                'unique_together': {('publication', 'relative_path')},
            },
        ),
        migrations.CreateModel(
            name='ReservedResourceRecord',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('_created', models.DateTimeField(auto_now_add=True)),
                ('_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('resource', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskReservedResourceRecord',
            fields=[
                ('pulp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.reservedresourcerecord')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.task')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='reservedresourcerecord',
            name='tasks',
            field=models.ManyToManyField(related_name='reserved_resources_record', through='core.TaskReservedResourceRecord', to='core.Task'),
        ),
        migrations.DeleteModel(
            name='ProgressBar',
        ),
        migrations.DeleteModel(
            name='ProgressSpinner',
        ),
        migrations.RemoveField(
            model_name='task',
            name='non_fatal_errors',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='_created',
            new_name='pulp_created',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='_id',
            new_name='pulp_id',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='_last_updated',
            new_name='pulp_last_updated',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='_type',
            new_name='pulp_type',
        ),
        migrations.RenameField(
            model_name='repository',
            old_name='_created',
            new_name='pulp_created',
        ),
        migrations.RenameField(
            model_name='repository',
            old_name='_id',
            new_name='pulp_id',
        ),
        migrations.RenameField(
            model_name='repository',
            old_name='_last_updated',
            new_name='pulp_last_updated',
        ),
        migrations.RenameField(
            model_name='reservedresource',
            old_name='_created',
            new_name='pulp_created',
        ),
        migrations.RenameField(
            model_name='reservedresource',
            old_name='_id',
            new_name='pulp_id',
        ),
        migrations.RenameField(
            model_name='reservedresource',
            old_name='_last_updated',
            new_name='pulp_last_updated',
        ),
        migrations.RenameField(
            model_name='reservedresourcerecord',
            old_name='_created',
            new_name='pulp_created',
        ),
        migrations.RenameField(
            model_name='reservedresourcerecord',
            old_name='_id',
            new_name='pulp_id',
        ),
        migrations.RenameField(
            model_name='reservedresourcerecord',
            old_name='_last_updated',
            new_name='pulp_last_updated',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='_created',
            new_name='pulp_created',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='_id',
            new_name='pulp_id',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='_last_updated',
            new_name='pulp_last_updated',
        ),
        migrations.AlterField(
            model_name='contentartifact',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.content', to_field='pulp_id'),
        ),
        migrations.AlterField(
            model_name='createdresource',
            name='task',
            field=models.ForeignKey(default=pulpcore.app.models.task.Task.current, on_delete=django.db.models.deletion.CASCADE, related_name='created_resources', to='core.task', to_field='pulp_id'),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to='core.task', to_field='pulp_id'),
        ),
        migrations.AlterField(
            model_name='publishedmetadata',
            name='content_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='published_metadata', serialize=False, to='core.content', to_field='pulp_id'),
        ),
        migrations.AlterField(
            model_name='publishedmetadata',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_metadata', to='core.publication', to_field='pulp_id'),
        ),
        migrations.AlterField(
            model_name='repositorycontent',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version_memberships', to='core.content', to_field='pulp_id'),
        ),
        migrations.AlterField(
            model_name='repositorycontent',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.repository', to_field='pulp_id'),
        ),
        migrations.AlterField(
            model_name='repositorycontent',
            name='version_added',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_memberships', to='core.repositoryversion', to_field='pulp_id'),
        ),
        migrations.AlterField(
            model_name='repositorycontent',
            name='version_removed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='removed_memberships', to='core.repositoryversion', to_field='pulp_id'),
        ),
        migrations.AlterField(
            model_name='repositoryversion',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.repository', to_field='pulp_id'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='parent',
        ),
        migrations.AlterField(
            model_name='taskreservedresource',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.reservedresource', to_field='pulp_id'),
        ),
        migrations.AlterField(
            model_name='taskreservedresource',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.task', to_field='pulp_id'),
        ),
        migrations.AlterField(
            model_name='taskreservedresourcerecord',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.reservedresourcerecord', to_field='pulp_id'),
        ),
        migrations.AlterField(
            model_name='taskreservedresourcerecord',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.task', to_field='pulp_id'),
        ),
        migrations.AlterField(
            model_name='contentartifact',
            name='relative_path',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='publishedmetadata',
            name='relative_path',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='FileSystemExporter',
            fields=[
                ('pulp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('pulp_type', models.TextField(default=None)),
                ('name', models.TextField(db_index=True, unique=True)),
                ('path', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Exporter',
        ),
        migrations.AddField(
            model_name='repository',
            name='pulp_type',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='repository',
            name='name',
            field=models.TextField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='reservedresource',
            name='resource',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='reservedresourcerecord',
            name='resource',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='SigningService',
            fields=[
                ('pulp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.TextField(db_index=True, unique=True)),
                ('script', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AsciiArmoredDetachedSigningService',
            fields=[
                ('signingservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.signingservice')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.signingservice',),
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
        migrations.RenameField(
            model_name='repository',
            old_name='last_version',
            new_name='next_version',
        ),
    ]
