# Generated by Django 4.2.22 on 2025-07-15 09:03

import django.contrib.postgres.fields
from django.db import migrations, models


ADD_RVC_CONSTRAINTS_TRIGGER_UP = """
CREATE FUNCTION post_repository_version_delete() RETURNS trigger AS 
$$
BEGIN
  UPDATE core_content SET repository_version_ids = array_remove(repository_version_ids, OLD.pulp_id) WHERE ARRAY[OLD.pulp_id] <@ repository_version_ids;
  RETURN null;
END;
$$
LANGUAGE plpgsql;

CREATE FUNCTION check_repositoryversion_content_fk() RETURNS trigger AS
$$
BEGIN
  IF (SELECT COUNT(rv_ids.id) FROM (SELECT unnest(NEW.repository_version_ids) AS id) AS rv_ids WHERE NOT EXISTS (SELECT pulp_id FROM core_repositoryversion WHERE pulp_id = rv_ids.id)) > 0 THEN
    RAISE EXCEPTION 'Foreign key in array field failed.';
  END IF;
  RETURN NEW;
END;
$$
LANGUAGE plpgsql;

CREATE TRIGGER repository_version_delete
  AFTER DELETE
  ON core_repositoryversion
  FOR EACH ROW
  EXECUTE FUNCTION post_repository_version_delete()
;

CREATE CONSTRAINT TRIGGER check_repository_version_fk
  AFTER INSERT OR UPDATE OF repository_version_ids
  ON core_content FROM core_repositoryversion
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW
  EXECUTE FUNCTION check_repositoryversion_content_fk()
;
"""
ADD_RVC_CONSTRAINTS_TRIGGER_DOWN = """
DROP TRIGGER IF EXISTS check_repository_version_fk ON core_content;
DROP TRIGGER IF EXISTS repository_version_delete ON core_repositoryversion;
DROP FUNCTION IF EXISTS check_repositoryversion_content_fk;
DROP FUNCTION IF EXISTS post_repository_version_delete;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0133_repositoryversion_content_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="repository_version_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.UUIDField(), default=list, size=None
            ),
        ),
        migrations.RunSQL(
            sql=ADD_RVC_CONSTRAINTS_TRIGGER_UP,
            reverse_sql=ADD_RVC_CONSTRAINTS_TRIGGER_DOWN,
        ),
    ]
